apiVersion: core.platform-mesh.org/v1alpha1
kind: AccountInfo
metadata:
  name: account
spec:
  account:
    generatedClusterId: "test-cluster"
    name: "test"
    originClusterId: "test-origin"
    path: "/test"
    type: "test"
    url: "http://test"
  fga:
    store:
      id: "openmfp"
  clusterInfo:
    ca: "test-ca"
  organization:
    generatedClusterId: "org-cluster"
    name: "test-org"
    originClusterId: "org-origin"
    path: "/org"
    type: "org"
    url: "http://org"
