all: false
force-file-write: true
formatter: goimports
log-level: info
recursive: false
require-template-schema-exists: true
template: testify
template-schema: '{{.Template}}.schema.json'
dir: 'pkg/resolver/mocks'
pkgname: mocks
structname: '{{.InterfaceName}}'
packages:
  k8s.io/apimachinery/pkg/api/meta:
    config:
      include-interface-regex: RESTMapper
      filename: restmapper.go
  sigs.k8s.io/controller-runtime/pkg/kcp:
    config:
      filename: kcp.go
  sigs.k8s.io/controller-runtime/pkg/client:
    config:
      include-interface-regex: Client
      filename: k8sclient.go
  github.com/openfga/api/proto/openfga/v1:
    config:
      dir: 'pkg/handler/mocks'
      include-interface-regex: OpenFGAServiceClient
      filename: openfgaclient.go
