all: false
force-file-write: true
formatter: goimports
log-level: info
recursive: false
require-template-schema-exists: true
template: testify
template-schema: '{{.Template}}.schema.json'
dir: 'pkg/handler/mocks'
pkgname: mocks
structname: '{{.InterfaceName}}'
filename: '{{.InterfaceName}}.go'
packages:
  github.com/openfga/api/proto/openfga/v1:
    config:
      include-interface-regex: OpenFGAServiceClient
  github.com/platform-mesh/rebac-authz-webhook/pkg/restmapper:
    config:
      include-interface-regex: Provider
  sigs.k8s.io/controller-runtime/pkg/client:
    config:
      include-interface-regex: ^Client
  sigs.k8s.io/controller-runtime/pkg/cluster:
    config:
      include-interface-regex: Cluster
  sigs.k8s.io/multicluster-runtime/pkg/manager:
    config:
      include-interface-regex: Manager
