version = 1
SPDX-PackageName = "rebac-authz-webhook"
SPDX-PackageDownloadLocation = "https://github.com/platform-mesh/rebac-authz-webhook"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 SAP SE or an SAP affiliate company and Platform Mesh contributors and rebac-authz-webhook contributors."
SPDX-License-Identifier = "Apache-2.0"