// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"sigs.k8s.io/controller-runtime/pkg/cluster"
)

// NewStoreCacheProvider creates a new instance of StoreCacheProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStoreCacheProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *StoreCacheProvider {
	mock := &StoreCacheProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StoreCacheProvider is an autogenerated mock type for the Provider type
type StoreCacheProvider struct {
	mock.Mock
}

type StoreCacheProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *StoreCacheProvider) EXPECT() *StoreCacheProvider_Expecter {
	return &StoreCacheProvider_Expecter{mock: &_m.Mock}
}

// Engage provides a mock function for the type StoreCacheProvider
func (_mock *StoreCacheProvider) Engage(context1 context.Context, s string, cluster1 cluster.Cluster) error {
	ret := _mock.Called(context1, s, cluster1)

	if len(ret) == 0 {
		panic("no return value specified for Engage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, cluster.Cluster) error); ok {
		r0 = returnFunc(context1, s, cluster1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StoreCacheProvider_Engage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Engage'
type StoreCacheProvider_Engage_Call struct {
	*mock.Call
}

// Engage is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - cluster1 cluster.Cluster
func (_e *StoreCacheProvider_Expecter) Engage(context1 interface{}, s interface{}, cluster1 interface{}) *StoreCacheProvider_Engage_Call {
	return &StoreCacheProvider_Engage_Call{Call: _e.mock.On("Engage", context1, s, cluster1)}
}

func (_c *StoreCacheProvider_Engage_Call) Run(run func(context1 context.Context, s string, cluster1 cluster.Cluster)) *StoreCacheProvider_Engage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 cluster.Cluster
		if args[2] != nil {
			arg2 = args[2].(cluster.Cluster)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *StoreCacheProvider_Engage_Call) Return(err error) *StoreCacheProvider_Engage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StoreCacheProvider_Engage_Call) RunAndReturn(run func(context1 context.Context, s string, cluster1 cluster.Cluster) error) *StoreCacheProvider_Engage_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type StoreCacheProvider
func (_mock *StoreCacheProvider) Get(s string) (string, bool) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (string, bool)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// StoreCacheProvider_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type StoreCacheProvider_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - s string
func (_e *StoreCacheProvider_Expecter) Get(s interface{}) *StoreCacheProvider_Get_Call {
	return &StoreCacheProvider_Get_Call{Call: _e.mock.On("Get", s)}
}

func (_c *StoreCacheProvider_Get_Call) Run(run func(s string)) *StoreCacheProvider_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *StoreCacheProvider_Get_Call) Return(s1 string, b bool) *StoreCacheProvider_Get_Call {
	_c.Call.Return(s1, b)
	return _c
}

func (_c *StoreCacheProvider_Get_Call) RunAndReturn(run func(s string) (string, bool)) *StoreCacheProvider_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type StoreCacheProvider
func (_mock *StoreCacheProvider) Start(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StoreCacheProvider_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type StoreCacheProvider_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - context1 context.Context
func (_e *StoreCacheProvider_Expecter) Start(context1 interface{}) *StoreCacheProvider_Start_Call {
	return &StoreCacheProvider_Start_Call{Call: _e.mock.On("Start", context1)}
}

func (_c *StoreCacheProvider_Start_Call) Run(run func(context1 context.Context)) *StoreCacheProvider_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *StoreCacheProvider_Start_Call) Return(err error) *StoreCacheProvider_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StoreCacheProvider_Start_Call) RunAndReturn(run func(context1 context.Context) error) *StoreCacheProvider_Start_Call {
	_c.Call.Return(run)
	return _c
}
