// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewTracker creates a new instance of Tracker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTracker(t interface {
	mock.TestingT
	Cleanup(func())
}) *Tracker {
	mock := &Tracker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Tracker is an autogenerated mock type for the Tracker type
type Tracker struct {
	mock.Mock
}

type Tracker_Expecter struct {
	mock *mock.Mock
}

func (_m *Tracker) EXPECT() *Tracker_Expecter {
	return &Tracker_Expecter{mock: &_m.Mock}
}

// Retried provides a mock function for the type Tracker
func (_mock *Tracker) Retried(key any) {
	_mock.Called(key)
	return
}

// Tracker_Retried_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Retried'
type Tracker_Retried_Call struct {
	*mock.Call
}

// Retried is a helper method to define mock.On call
//   - key any
func (_e *Tracker_Expecter) Retried(key interface{}) *Tracker_Retried_Call {
	return &Tracker_Retried_Call{Call: _e.mock.On("Retried", key)}
}

func (_c *Tracker_Retried_Call) Run(run func(key any)) *Tracker_Retried_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Tracker_Retried_Call) Return() *Tracker_Retried_Call {
	_c.Call.Return()
	return _c
}

func (_c *Tracker_Retried_Call) RunAndReturn(run func(key any)) *Tracker_Retried_Call {
	_c.Run(run)
	return _c
}

// ShouldRetry provides a mock function for the type Tracker
func (_mock *Tracker) ShouldRetry(key any) bool {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for ShouldRetry")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(any) bool); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Tracker_ShouldRetry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShouldRetry'
type Tracker_ShouldRetry_Call struct {
	*mock.Call
}

// ShouldRetry is a helper method to define mock.On call
//   - key any
func (_e *Tracker_Expecter) ShouldRetry(key interface{}) *Tracker_ShouldRetry_Call {
	return &Tracker_ShouldRetry_Call{Call: _e.mock.On("ShouldRetry", key)}
}

func (_c *Tracker_ShouldRetry_Call) Run(run func(key any)) *Tracker_ShouldRetry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Tracker_ShouldRetry_Call) Return(b bool) *Tracker_ShouldRetry_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Tracker_ShouldRetry_Call) RunAndReturn(run func(key any) bool) *Tracker_ShouldRetry_Call {
	_c.Call.Return(run)
	return _c
}
