clusters:
- name: webhook
  cluster:
    certificate-authority: /config/ca.crt
    server: https://host.containers.internal:4443/authz
users:
- name: api-server
  user:
    token: test-token
current-context: webhook
contexts:
- context:
    cluster: webhook
    user: api-server
  name: webhook