name: ci
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  pipe:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    uses: platform-mesh/.github/.github/workflows/pipeline-golang-app.yml@6fe9408e82042eca1b50ca8b065e32f769b35723 # ci/with-token-arg
    secrets: inherit
    with:
      imageTagName: ghcr.io/platform-mesh/rebac-authz-webhook
      useTask: true
      useLocalCoverageConfig: true
      coverageThresholdTotal: 80