name: ci
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  pipe:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    uses: platform-mesh/.github/.github/workflows/pipeline-golang-app.yml@ci/with-token-arg
    secrets: inherit
    with:
      imageTagName: ghcr.io/platform-mesh/rebac-authz-webhook
      useTask: true
      coverageThresholdFile: 0
      coverageThresholdPackage: 0
      coverageThresholdTotal: 0